#+TITLE: Meta-Barcoding Dual-Indexing
#+AUTHOR: Markus Ankenbrand

* About
This is a collection of the computational methods used for the publication <Link will be included when available>.
Here we provide all custom scripts and commands to replicate our results.
Furthermore you can download the pre-computed training sets for the RDPclassifier <Link> and UTAX <Link>.
If you find this information useful please consider citing our article <Link>.

* Data
If you are just interested in the pre-computed training sets go to releases and download the tar-ball.
There you can find the training sets in the subfolder training.

* Dependencies
This is a list of software tools and versions used in the original analysis.
We provide precomputed results for most steps so don't worry if you can't get a certain tool in a certain version.
If you get substantially different results (e.g. using other versions/tools) feel free to contact me.
You can also do so by opening an Issue here on GitHub.
** Hardware
Most of the analyses were performed on a Laptop with
 - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz Processor
 - 16GB RAM
 - Ubuntu 14.04 operating system
Only the RDP training was performed on a machine with more RAM available.
** Third party tools
 - [[http://its2.bioapps.biozentrum.uni-wuerzburg.de/][ITS2 database]] (Version 4.0.0 and inofficial release (included))
 - UTAX 
 - RDPclassifier 
 - NCBI::Taxonomy - perl module
 - R
** Scripts

* Workflow
** Preparation of Reference Database
*** Data
The ITS2 sequences can be retrieved from the ITS2 database.
The previous reference db consisted of all "Direct folds & Homology modeled" sequences from "Viridiplantae" (db version v4.0.0, 2011).
This file is included for comparison.
The new reference database consists of all sequences from "Viridiplantae" of an inofficial ITS2 database release (2014).
This file is also included in this repository.
*** Taxonomic assignment
*** UTAX training
*** RDP training
** Analysis of Pollen Samples
*** Preprocessing
*** Classification
*** Species accumulation curves
