#+TITLE: Meta-Barcoding Dual-Indexing
#+AUTHOR: Markus Ankenbrand

* About
This is a collection of the computational methods used for the publication <Link will be included when available>.
Here we provide all custom scripts and commands to replicate our results.
Furthermore you can download the pre-computed training sets for the RDPclassifier <Link> and UTAX <Link>.
If you find this information useful please consider citing our article <Link>.

* Data
If you are just interested in the pre-computed training sets go to releases and download the tar-ball.
There you can find the training sets in the subfolder training.

* Dependencies
This is a list of software tools and versions used in the original analysis.
We provide precomputed results for most steps so don't worry if you can't get a certain tool in a certain version.
If you get substantially different results (e.g. using other versions/tools) feel free to contact me.
You can also do so by opening an Issue here on GitHub.
** Hardware
** Third party tools
** Scripts
